# Generated by Django 4.1.7 on 2023-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prokhelo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='admin',
            name='private_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
